languages = ["english", "italian", "german", "russian", "spanish"]
print(languages[3])
print(languages[-1])
message = f"I am currently learning {languages[3].title()}."
print(message)
languages.append("japanese")
print(languages)
languages.insert(1, "chinese")
print(languages)
del languages[-1]
print(languages)
languages.append("japanese")
print(languages)
samauri = languages.pop()
print(languages)
print(samauri.title())
roosky = languages.pop(4)
print(languages)
print(roosky.title())
print(languages)
languages.remove('german')
print(languages)
print(sorted(languages))
print(languages)
languages.sort()
print(languages)
languages.sort(reverse=True)
print(languages)
languages.reverse()
print(languages)
print(len(languages))